name: launches
description: "A flutter app, that list all programmed spaceX rocket launches"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.png
  fonts:
    - family: Bungee
      fonts:
        - asset: assets/Bungee-Regular.ttf
